# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-slim

# Install dependencies for native modules
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates git build-essential python3 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy package and install dependencies
COPY package.json tsconfig.json .
RUN npm install

# Copy source files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (stdio doesn't require HTTP port)

# Start the MCP stdio server
ENTRYPOINT ["node", "dist/src/mcp-stdio-server.js"]
